### ISSUE TITLE
AS4 Unable to verify certificate of receiving access point

### ISSUE THREAD

**Issue by itEnercomSwiss** [OxalisCommunity/Oxalis-AS4#97]
Hi,
I have the following problem.
I use OXALIS 4.1.1 and OXALIS AS4 4.1.6 on Tomcat Server. I took the .p12 test certificate from the PEPPOL procedure and I find myself at the first step of the OnBoard Test with this result:

> **Transaction (with instance identifier POP000053-77-20200226T105650) to testing AP failed to be delivered. Error; Unable to verify certificate of receiving access point**

I followed the comments in the following posts:
- https://github.com/difi/Oxalis-AS4/issues/55
- https://github.com/difi/Oxalis-AS4/issues/67

but not yet able to solve the problem.
My oxalis.conf:

> oxalis.keystore {
>      # Relative to OXALIS_HOME
>      path=peppol_test.p12
>      password = password
>      key.alias = peppol_test
>      key.password = password
>  }
> 
>  # The relative name of the directory holding plugin
>  oxalis.path.plugin = /opt/oxalis/as4
> 
>  # Signals to Oxalis that we should look for plugin
>  # oxalis.persister.receipt = plugin
> 
>  # Where to store inbound files
>  oxalis.path.inbound = /opt/message/in
> 
>  # Optional
>  oxalis.logging.config=logback.xml

Thanks.
Best 
Davide

![Schermata 2020-02-26 alle 12 10 41](https://user-images.githubusercontent.com/41580809/75339822-8bf7da80-5891-11ea-9977-6177d0232e72.png)

**Comment by FrodeBjerkholt** [comment]
Do you see anything in the logs of your AP when sending from the TestBed? Perhaps the "Unable to verify certificate of receiving access point" is a test the TestBed does before attempting to send a message?

**Comment by itEnercomSwiss** [comment]
Hi,
I don't see any error o other log in my access point. Could it depend on how I configured the p12 keystore?

Thanks

**Comment by FrodeBjerkholt** [comment]
If you do not see anything in the logs of your AP - I think the best thing is to ask support at OpenPeppol TestBed. Hopefully they can tell what is wrong. Maybe the HTTPS configuration is not accepted?

**Comment by itEnercomSwiss** [comment]
The HTTPS configuration respects Peppol's AS4 rules.

**Comment by itEnercomSwiss** [comment]
Hi.
I asked for OpenPeppol Testbed support. They reset the platform, with but the problem still persists. What could be the cause?

Thanks

**Comment by FrodeBjerkholt** [comment]
I don't know. Can you ask them where the "Unable to verify certificate of receiving access point" message comes from?

**Comment by wiredhands** [comment]
Hi

I actually had the exact same error when I did the enrolling test for AS4.

As it turned out for me it was because the certificates were mismatched, between the browser i enrolled with and our AS4 endpoint.

At first I had made a keystore for the AS4 endpoint, but left the original certificate on the browser.

Then when I enrolled for the test, I had the same error as you got.

What I found out is that You have to make absolutely sure that your AS4 endpoint is running on the same certificate as the one you use in your browser to enroll for the AS4 test, otherwise you will get the error you posted.

What I did to solve it was to create a keystore for the AS4 endpoint and then also a matching keystore in a format that I could import into the browser I would enroll for the onboarding with. This ensures that I have the exact same certificates in the browser as I have on the AS4 endpoint.

This ensured that when I enrolled the process could actually reach my endpoint because the certificates in my browser and on the server matched.

I hope my description isn't to convoluted and that it helps you to get further in the enrolment process

Best regards
R

**Comment by itEnercomSwiss** [comment]
Hello.

Thanks for your email.
I will absolutely follow your advice. I update you when I have news.

Thanks

**Comment by aaron-kumar** [comment]
More than 30 months older issue

@itEnercomSwiss still facing issue?
I am closing this issue for time being. If you are still facing this issue, please feel free to reopen this issue.
